# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aiv.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.centralLayout.setObjectName("centralLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.centralLayout.addWidget(self.graphicsView)
        self.toolBox = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setObjectName("toolBox")
        self.toolLayout = QtWidgets.QVBoxLayout(self.toolBox)
        self.toolLayout.setObjectName("toolLayout")
        self.colorsSelect = QtWidgets.QComboBox(self.toolBox)
        self.colorsSelect.setObjectName("colorsSelect")
        self.colorsSelect.addItem("")
        self.colorsSelect.addItem("")
        self.colorsSelect.addItem("")
        self.toolLayout.addWidget(self.colorsSelect)
        self.buttonBox = QtWidgets.QWidget(self.toolBox)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonLayout = QtWidgets.QGridLayout(self.buttonBox)
        self.buttonLayout.setObjectName("buttonLayout")
        self.widthBox = QtWidgets.QWidget(self.buttonBox)
        self.widthBox.setObjectName("widthBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widthBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widthLabel = QtWidgets.QLabel(self.widthBox)
        self.widthLabel.setObjectName("widthLabel")
        self.horizontalLayout_3.addWidget(self.widthLabel)
        self.widthSpin = QtWidgets.QSpinBox(self.widthBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthSpin.sizePolicy().hasHeightForWidth())
        self.widthSpin.setSizePolicy(sizePolicy)
        self.widthSpin.setMinimum(1)
        self.widthSpin.setMaximum(1024)
        self.widthSpin.setProperty("value", 16)
        self.widthSpin.setObjectName("widthSpin")
        self.horizontalLayout_3.addWidget(self.widthSpin)
        self.buttonLayout.addWidget(self.widthBox, 4, 0, 1, 1)
        self.zoomBox = QtWidgets.QWidget(self.buttonBox)
        self.zoomBox.setObjectName("zoomBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.zoomBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.zoomLabel = QtWidgets.QLabel(self.zoomBox)
        self.zoomLabel.setObjectName("zoomLabel")
        self.horizontalLayout_2.addWidget(self.zoomLabel)
        self.zoomSpin = QtWidgets.QSpinBox(self.zoomBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomSpin.sizePolicy().hasHeightForWidth())
        self.zoomSpin.setSizePolicy(sizePolicy)
        self.zoomSpin.setMinimum(1)
        self.zoomSpin.setMaximum(20)
        self.zoomSpin.setProperty("value", 2)
        self.zoomSpin.setObjectName("zoomSpin")
        self.horizontalLayout_2.addWidget(self.zoomSpin)
        self.buttonLayout.addWidget(self.zoomBox, 4, 1, 1, 1)
        self.prevpalButton = QtWidgets.QPushButton(self.buttonBox)
        self.prevpalButton.setObjectName("prevpalButton")
        self.buttonLayout.addWidget(self.prevpalButton, 1, 0, 1, 1)
        self.nextimgButton = QtWidgets.QPushButton(self.buttonBox)
        self.nextimgButton.setObjectName("nextimgButton")
        self.buttonLayout.addWidget(self.nextimgButton, 0, 1, 1, 1)
        self.previmgButton = QtWidgets.QPushButton(self.buttonBox)
        self.previmgButton.setObjectName("previmgButton")
        self.buttonLayout.addWidget(self.previmgButton, 0, 0, 1, 1)
        self.nextpalButton = QtWidgets.QPushButton(self.buttonBox)
        self.nextpalButton.setObjectName("nextpalButton")
        self.buttonLayout.addWidget(self.nextpalButton, 1, 1, 1, 1)
        self.toolLayout.addWidget(self.buttonBox)
        self.tilemapCheck = QtWidgets.QCheckBox(self.toolBox)
        self.tilemapCheck.setObjectName("tilemapCheck")
        self.toolLayout.addWidget(self.tilemapCheck)
        self.inputBox = QtWidgets.QWidget(self.toolBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputBox.sizePolicy().hasHeightForWidth())
        self.inputBox.setSizePolicy(sizePolicy)
        self.inputBox.setObjectName("inputBox")
        self.inputLayout = QtWidgets.QFormLayout(self.inputBox)
        self.inputLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.inputLayout.setObjectName("inputLayout")
        self.imageLabel = QtWidgets.QLabel(self.inputBox)
        self.imageLabel.setObjectName("imageLabel")
        self.inputLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.imageLabel)
        self.imageInput = QtWidgets.QLineEdit(self.inputBox)
        self.imageInput.setObjectName("imageInput")
        self.inputLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.imageInput)
        self.paletteLabel = QtWidgets.QLabel(self.inputBox)
        self.paletteLabel.setObjectName("paletteLabel")
        self.inputLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.paletteLabel)
        self.paletteInput = QtWidgets.QLineEdit(self.inputBox)
        self.paletteInput.setObjectName("paletteInput")
        self.inputLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.paletteInput)
        self.tilemapLabel = QtWidgets.QLabel(self.inputBox)
        self.tilemapLabel.setEnabled(False)
        self.tilemapLabel.setObjectName("tilemapLabel")
        self.inputLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.tilemapLabel)
        self.tilemapInput = QtWidgets.QLineEdit(self.inputBox)
        self.tilemapInput.setEnabled(False)
        self.tilemapInput.setObjectName("tilemapInput")
        self.inputLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.tilemapInput)
        self.toolLayout.addWidget(self.inputBox)
        self.centralLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSaveImage = QtWidgets.QAction(MainWindow)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSaveImage)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.colorsSelect.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Advance Image Viewer"))
        self.colorsSelect.setItemText(0, _translate("MainWindow", "4 Colors (2bpp)"))
        self.colorsSelect.setItemText(1, _translate("MainWindow", "16 Colors (4bpp)"))
        self.colorsSelect.setItemText(2, _translate("MainWindow", "256 Colors (8bpp)"))
        self.widthLabel.setText(_translate("MainWindow", "Width"))
        self.zoomLabel.setText(_translate("MainWindow", "Zoom"))
        self.zoomSpin.setSuffix(_translate("MainWindow", "x"))
        self.prevpalButton.setText(_translate("MainWindow", "Previous Palette"))
        self.nextimgButton.setText(_translate("MainWindow", "Next Image"))
        self.previmgButton.setText(_translate("MainWindow", "Previous Image"))
        self.nextpalButton.setText(_translate("MainWindow", "Next Palette"))
        self.tilemapCheck.setText(_translate("MainWindow", "Enable Tilemap"))
        self.imageLabel.setText(_translate("MainWindow", "Image"))
        self.paletteLabel.setText(_translate("MainWindow", "Palette"))
        self.tilemapLabel.setText(_translate("MainWindow", "Tilemap"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open ROM"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSaveImage.setText(_translate("MainWindow", "Save Image"))

